DROP TABLE GASTOS;
DROP TABLE TARJETA;
CREATE TABLE TARJETA (ID_TARJETA INTEGER PRIMARY KEY AUTO_INCREMENT,
        NOMBRE VARCHAR(180), DIA_CORTE INTEGER);
DESCRIBE  TARJETA;

CREATE TABLE GASTOS (ID_GASTOS INTEGER PRIMARY KEY AUTO_INCREMENT,
                    ID_TARJETA INTEGER, CONCEPTO VARCHAR(280), FECHA DATE,
     CANTIDAD FLOAT, FOREIGN KEY(ID_TARJETA) REFERENCES TARJETA(ID_TARJETA));

select * from GASTOS;
select * from TARJETA;