
CREATE TABLE TARJETA (ID_TARJETA INTEGER AUTO_INCREMENT PRIMARY KEY,
                   NOMBRE VARCHAR(180), DIA_CORTE INTEGER
                      );

CREATE TABLE GASTOS(ID_GASTO INTEGER AUTO_INCREMENT PRIMARY KEY,
                    ID_TARJETA INTEGER, CONCEPTO VARCHAR(280),
                    FECHA DATE,
                    CANTIDAD FLOAT,
        FOREIGN KEY (ID_TARJETA) REFERENCES TARJETA(ID_TARJETA));
